# services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: false

  post.event:
    class: 'Vigihdev\WpEventDispatcher\Event\PostSubscriber'

  Vigihdev\WpEventDispatcher\Contracts\PostDispatcherInterface:
    class: 'Vigihdev\WpEventDispatcher\Event\PostDispatcher'
    public: true
    calls:
      - method: addSubscriber
        arguments:
          - "@post.event"
